version: "3.8"
services:

    appserver:
        restart: always
        build:
            context: ./server
        ports:
            - "3000:3000"
        depends_on: 
            - "facerec"
            - "rabbitmq"
        container_name: AppServer
        
    facerec:
        restart: always
        build:
            context: ./FaceRec
        depends_on: 
            - "rabbitmq"
        container_name: FaceRec
        
    rabbitmq:
        image: rabbitmq:3
        container_name: RabbitMQ

    facerecapi:
        restart: always
        build:
            context: ./FaceRecAPI
        depends_on: 
            - "rabbitmq"
        container_name: FaceRecAPI
    
    rabbitmq:
        image: rabbitmq:3
        container_name: RabbitMQ

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - "appserver"
            - "facerec"
            - "rabbitmq"
        container_name: Nginx
