version: "3.8"
services:
    nodeserver:
        build:
            context: ./server
        ports:
            - "3000:3000"
    facerec:
        build:
            context: ./FaceRec
        ports: 
            - "3001:3001"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"