version: "3.8"
services:
    appserver:
        build:
            context: ./server
        ports:
            - "3000:3000"
        depends_on: 
            - "facerec"
            - "rabbitmq"
        container_name: AppServer
    facerec:
        build:
            context: ./FaceRec
        depends_on: 
            - "rabbitmq"
        container_name: FaceRec
    rabbitmq:
        image: rabbitmq:3
        container_name: RabbitMQ
