version: "3.8"
services:
    appserver:
        build:
            context: ./server
        ports:
            - "3000:3000"
    facerec:
        build:
            context: ./FaceRec
        ports: 
            - "3001:3001"
        depends_on: 
            - "appserver"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - "appserver"